version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///db.sqlite3
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
      - ADMIN_IDS=${ADMIN_IDS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bot:
    build: .
    command: python bot_handler.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
      - BACKEND_URL=http://api:8000
      - ADMIN_IDS=${ADMIN_IDS}
    volumes:
      - ./.env:/app/.env
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: hookah-network
